proc export_artifacts {} {
    set run_dir [file join $::cfg(project_dir) ${::cfg(project_name)}.runs $::cfg(run_name)]
    set hwh_file [file join $::cfg(project_dir) ${::cfg(project_name)}.gen sources_1 bd $::cfg(bd_name) hw_handoff ${::cfg(bd_name)}.hwh]

    file mkdir $::cfg(export_dir)
    file copy -force [file join $run_dir ${::cfg(top)}.bit] [file join $::cfg(export_dir) ${::cfg(top)}.bit]
    file copy -force $hwh_file [file join $::cfg(export_dir) ${::cfg(bd_name)}.hwh]
    file copy -force [file join $run_dir ${::cfg(top)}.bit] [file join $::cfg(export_dir) ${::cfg(pynq_name)}.bit]
    file copy -force $hwh_file [file join $::cfg(export_dir) ${::cfg(pynq_name)}.hwh]
    file copy -force [file join $run_dir ${::cfg(top)}_route_status.rpt] [file join $::cfg(export_dir) ${::cfg(top)}_route_status.rpt]
    file copy -force [file join $run_dir ${::cfg(top)}_timing_summary_final.rpt] [file join $::cfg(export_dir) ${::cfg(top)}_timing_summary_final.rpt]
    file copy -force [file join $run_dir ${::cfg(top)}_drc_final.rpt] [file join $::cfg(export_dir) ${::cfg(top)}_drc_final.rpt]

    set readme [open [file join $::cfg(export_dir) README.md] w]
    puts $readme "# $::cfg(export_name)"
    puts $readme ""
    puts $readme "Generated by the rebuild package Tcl flow."
    puts $readme ""
    puts $readme "- Vivado: $::cfg(vivado_version)"
    puts $readme "- Part: $::cfg(part)"
    puts $readme "- Board part: $::cfg(board_part)"
    puts $readme "- Run: $::cfg(run_name)"
    puts $readme "- Strategy: Performance_ExplorePostRoutePhysOpt"
    puts $readme "- PYNQ aliases: ${::cfg(pynq_name)}.bit, ${::cfg(pynq_name)}.hwh"
    puts $readme ""
    puts $readme "Check ${::cfg(top)}_route_status.rpt, ${::cfg(top)}_timing_summary_final.rpt, and ${::cfg(top)}_drc_final.rpt before using the generated bitstream."
    close $readme

    puts "EXPORT_DIR $::cfg(export_dir)"
}
